config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'

  resources :lists, only:  [:index, :new, :create, :show] do
    resources :items, only: [:new, :create]
  end

  resources :items, only:[:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  has_many :sub_items
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/models/sub_item.rb
class SubItem < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <link rel="apple-touch-icon" sizes="180x180" href=" <%= image_path 'favicon.png' %>">
    <%= favicon_link_tag asset_path('favicon.png') %>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="list-banner mb-3">
  <%= link_to new_list_path do  %>
    <%= image_tag "add.svg", alt: "add", class: 'add-icon' %>
  <% end %>
</div>

<div class="list-cards">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do  %>
      <div class="list-card">
        <%= image_tag "rectangle.svg", alt: "alttext" %>
        <span><%= list.name.upcase.truncate(20, omission: '..') %></span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<div class="title-banner">
  <div class="show-list-banner">
  </div>
  <h1 class="show-title"><%= @list.name.upcase %></h1>
</div>

<div class="item-cards">

  <% @list.items.each do |item| %>
    <div class="item-card">
      <svg width="40" height="40" viewBox="0 0 40 40" fill="<%= item.done ? '#C1CAD3' : 'none' %>" xmlns="http://www.w3.org/2000/svg">
        <circle cx="20" cy="20" r="17.5" stroke="#C1CAD3" stroke-width="5"/>
      </svg>

      <span><%= item.title %></span>
      <% if item.sub_items.present?  %>
        <%= image_tag "triangle.svg", alt: "triangle", class: "triangle", data: {
          triangleitemid: item.id
        } %>
      <% end %>
    </div>
    <% if item.sub_items.present?  %>
      <div class="item-fold" data-itemid='<%= item.id %>'>
        <ul>
          <% item.sub_items.each do |sub_item| %>
            <li >
              <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="7.5" cy="7.5" r="6.5" stroke="#C1CAD3" stroke-width="2"/>
              </svg>
              <span><%= sub_item.title %></span>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

<script>
  let buttons = document.querySelectorAll('.triangle')
  buttons.forEach((button) => {
    button.addEventListener('click', () => {
      var subItem = Array.from(document.querySelectorAll('[data-itemId]')).find(function(item){
        return item.dataset.itemid == button.dataset.triangleitemid;
      });
      // subItem.classList.toggle('d-none');
      subItem.classList.toggle('unfold');
      button.classList.toggle('turn-around');
      button.classList.toggle('unfolded');
    })
  })
</script>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>